playerHP = 20
playerMoney = 0
playerRep = 0
playerName = ""
playerName = input("Welcome, What is your name?:")
playerClass = ""
enemyAttack = 0
magicAttack = 0
rangeAttack = 0
meleeAttack = 0
magicDefence = 0
rangeDefence = 0
meleeDefence = 0
monstersKilled = 0
playerInput = ""
possibleMonsters = ["Rat", "Dog", "Dragon", "Human", "Druid", "Guard"]
activeMonster = ""
shop = ["Dagger - 6 Gold", "Shield - 10 Gold", "Cape - 4 Gold", "Whip - 25 Gold"]
